<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DS-PC" name="Tests" tests="38" failures="0" timestamp="18 Jul 2016 11:17:35 GMT" time="208.072" errors="0">
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Common.VerifyStaticLinks">
    <failure type="java.lang.Exception" message="TestCases.Common.VerifyStaticLinks : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Common.VerifyStaticLinks : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Common.VerifyStaticLinks.ExecutionStatusCheck(VerifyStaticLinks.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Common.ConcurrentLoginSessionCheck">
    <failure type="java.lang.Exception" message="TestCases.Common.ConcurrentLoginSessionCheck : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Common.ConcurrentLoginSessionCheck : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Common.ConcurrentLoginSessionCheck.ExecutionStatusCheck(ConcurrentLoginSessionCheck.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.AccountCancellation">
    <failure type="java.lang.Exception" message="TestCases.CRM.AccountCancellation : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.AccountCancellation : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.AccountCancellation.ExecutionStatusCheck(AccountCancellation.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.CustomerCredit">
    <failure type="java.lang.Exception" message="TestCases.CRM.CustomerCredit : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.CustomerCredit : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.CustomerCredit.ExecutionStatusCheck(CustomerCredit.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.DeliveryKeyStatus">
    <failure type="java.lang.Exception" message="TestCases.CRM.DeliveryKeyStatus : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.DeliveryKeyStatus : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.DeliveryKeyStatus.ExecutionStatusCheck(DeliveryKeyStatus.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.DonationOneTime">
    <failure type="java.lang.Exception" message="TestCases.CRM.DonationOneTime : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.DonationOneTime : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.DonationOneTime.ExecutionStatusCheck(DonationOneTime.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.DonationRecurring">
    <failure type="java.lang.Exception" message="TestCases.CRM.DonationRecurring : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.DonationRecurring : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.DonationRecurring.ExecutionStatusCheck(DonationRecurring.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.GiftCertificateByEmail">
    <failure type="java.lang.Exception" message="TestCases.CRM.GiftCertificateByEmail : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.GiftCertificateByEmail : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.GiftCertificateByEmail.ExecutionStatusCheck(GiftCertificateByEmail.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.GiftCertificateByHand">
    <failure type="java.lang.Exception" message="TestCases.CRM.GiftCertificateByHand : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.GiftCertificateByHand : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.GiftCertificateByHand.ExecutionStatusCheck(GiftCertificateByHand.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.LateCancel">
    <failure type="java.lang.Exception" message="TestCases.CRM.LateCancel : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.LateCancel : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.LateCancel.ExecutionStatusCheck(LateCancel.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OrderItemCredit">
    <failure type="java.lang.Exception" message="TestCases.CRM.OrderItemCredit : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OrderItemCredit : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OrderItemCredit.ExecutionStatusCheck(OrderItemCredit.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OrderLevelCredit">
    <failure type="java.lang.Exception" message="TestCases.CRM.OrderLevelCredit : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OrderLevelCredit : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OrderLevelCredit.ExecutionStatusCheck(OrderLevelCredit.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OTPACHDecline">
    <failure type="java.lang.Exception" message="TestCases.CRM.OTPACHDecline : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OTPACHDecline : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OTPACHDecline.ExecutionStatusCheck(OTPACHDecline.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OTPACHSuccess">
    <failure type="java.lang.Exception" message="TestCases.CRM.OTPACHSuccess : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OTPACHSuccess : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OTPACHSuccess.ExecutionStatusCheck(OTPACHSuccess.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.NSFACH">
    <failure type="java.lang.Exception" message="TestCases.CRM.NSFACH : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.NSFACH : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.NSFACH.ExecutionStatusCheck(NSFACH.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.ACHRefund">
    <failure type="java.lang.Exception" message="TestCases.CRM.ACHRefund : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.ACHRefund : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.ACHRefund.ExecutionStatusCheck(ACHRefund.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OTPCCDecline">
    <failure type="java.lang.Exception" message="TestCases.CRM.OTPCCDecline : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OTPCCDecline : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OTPCCDecline.ExecutionStatusCheck(OTPCCDecline.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.OTPCCSuccess">
    <failure type="java.lang.Exception" message="TestCases.CRM.OTPCCSuccess : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.OTPCCSuccess : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.OTPCCSuccess.ExecutionStatusCheck(OTPCCSuccess.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.CheckRefund">
    <failure type="java.lang.Exception" message="TestCases.CRM.CheckRefund : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.CheckRefund : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.CheckRefund.ExecutionStatusCheck(CheckRefund.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.CCRefund">
    <failure type="java.lang.Exception" message="TestCases.CRM.CCRefund : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.CCRefund : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.CCRefund.ExecutionStatusCheck(CCRefund.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.Reactivation">
    <failure type="java.lang.Exception" message="TestCases.CRM.Reactivation : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.Reactivation : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.Reactivation.ExecutionStatusCheck(Reactivation.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.VacationCancel">
    <failure type="java.lang.Exception" message="TestCases.CRM.VacationCancel : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.VacationCancel : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.VacationCancel.ExecutionStatusCheck(VacationCancel.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.VacationCreate">
    <failure type="java.lang.Exception" message="TestCases.CRM.VacationCreate : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.VacationCreate : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.VacationCreate.ExecutionStatusCheck(VacationCreate.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.CreateTicket">
    <failure type="java.lang.Exception" message="TestCases.CRM.CreateTicket : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.CreateTicket : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.CreateTicket.ExecutionStatusCheck(CreateTicket.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.ERP.CheckDeposit">
    <failure type="java.lang.Exception" message="TestCases.ERP.CheckDeposit : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.ERP.CheckDeposit : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.ERP.CheckDeposit.ExecutionStatusCheck(CheckDeposit.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.CRM.NSFCheck">
    <failure type="java.lang.Exception" message="TestCases.CRM.NSFCheck : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.CRM.NSFCheck : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.CRM.NSFCheck.ExecutionStatusCheck(NSFCheck.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.AddSubscription">
    <failure type="java.lang.Exception" message="TestCases.Magento.AddSubscription : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.AddSubscription : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.AddSubscription.ExecutionStatusCheck(AddSubscription.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.DeleteSubscription">
    <failure type="java.lang.Exception" message="TestCases.Magento.DeleteSubscription : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.DeleteSubscription : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.DeleteSubscription.ExecutionStatusCheck(DeleteSubscription.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.Customization">
    <failure type="java.lang.Exception" message="TestCases.Magento.Customization : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.Customization : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.Customization.ExecutionStatusCheck(Customization.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.GuestDonateABox">
    <failure type="java.lang.Exception" message="TestCases.Magento.GuestDonateABox : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.GuestDonateABox : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.GuestDonateABox.ExecutionStatusCheck(GuestDonateABox.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.GuestGCPurchaseByEmail">
    <failure type="java.lang.Exception" message="TestCases.Magento.GuestGCPurchaseByEmail : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.GuestGCPurchaseByEmail : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.GuestGCPurchaseByEmail.ExecutionStatusCheck(GuestGCPurchaseByEmail.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.GuestGCPurchaseByHand">
    <failure type="java.lang.Exception" message="TestCases.Magento.GuestGCPurchaseByHand : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.GuestGCPurchaseByHand : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.GuestGCPurchaseByHand.ExecutionStatusCheck(GuestGCPurchaseByHand.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.Loginout">
    <failure type="java.lang.Exception" message="TestCases.Magento.Loginout : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.Loginout : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.Loginout.ExecutionStatusCheck(Loginout.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.SignupEmailConfirmationCheck">
    <failure type="java.lang.Exception" message="TestCases.Magento.SignupEmailConfirmationCheck : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.SignupEmailConfirmationCheck : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.SignupEmailConfirmationCheck.ExecutionStatusCheck(SignupEmailConfirmationCheck.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.Magento.UpdateBillingInfo">
    <failure type="java.lang.Exception" message="TestCases.Magento.UpdateBillingInfo : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.Magento.UpdateBillingInfo : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.Magento.UpdateBillingInfo.ExecutionStatusCheck(UpdateBillingInfo.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.SalesRep.SalesSignup">
    <failure type="java.lang.Exception" message="TestCases.SalesRep.SalesSignup : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.SalesRep.SalesSignup : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.SalesRep.SalesSignup.ExecutionStatusCheck(SalesSignup.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="@BeforeClass ExecutionStatusCheck" time="0.0" classname="TestCases.SalesRep.UploadTR">
    <failure type="java.lang.Exception" message="TestCases.SalesRep.UploadTR : Execution status is set to &amp;apos;No&amp;apos; in &amp;apos;ExecutionChecker.xls&amp;apos;">
      <![CDATA[java.lang.Exception: TestCases.SalesRep.UploadTR : Execution status is set to 'No' in 'ExecutionChecker.xls'
	at Operation.ExecutionStatusChecker.executetestcase(ExecutionStatusChecker.java:62)
	at TestCases.SalesRep.UploadTR.ExecutionStatusCheck(UploadTR.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ExecutionStatusCheck -->
  <testcase name="testVerifyStaticLinks" time="0.0" classname="TestCases.Common.VerifyStaticLinks">
    <skipped/>
  </testcase> <!-- testVerifyStaticLinks -->
  <testcase name="testConcurrentLoginSessionCheck" time="0.001" classname="TestCases.Common.ConcurrentLoginSessionCheck">
    <skipped/>
  </testcase> <!-- testConcurrentLoginSessionCheck -->
  <testcase name="testAccountCancellation" time="0.0" classname="TestCases.CRM.AccountCancellation">
    <skipped/>
  </testcase> <!-- testAccountCancellation -->
  <testcase name="testCustomerCredit" time="0.0" classname="TestCases.CRM.CustomerCredit">
    <skipped/>
  </testcase> <!-- testCustomerCredit -->
  <testcase name="testDeliveryKeyStatus" time="0.0" classname="TestCases.CRM.DeliveryKeyStatus">
    <skipped/>
  </testcase> <!-- testDeliveryKeyStatus -->
  <testcase name="testdonateonetime" time="0.001" classname="TestCases.CRM.DonationOneTime">
    <skipped/>
  </testcase> <!-- testdonateonetime -->
  <testcase name="testDonationRecurring" time="0.0" classname="TestCases.CRM.DonationRecurring">
    <skipped/>
  </testcase> <!-- testDonationRecurring -->
  <testcase name="testGiftCertificateByEmail" time="0.0" classname="TestCases.CRM.GiftCertificateByEmail">
    <skipped/>
  </testcase> <!-- testGiftCertificateByEmail -->
  <testcase name="testGiftCertificateByHand" time="0.0" classname="TestCases.CRM.GiftCertificateByHand">
    <skipped/>
  </testcase> <!-- testGiftCertificateByHand -->
  <testcase name="testLateCancel" time="0.0" classname="TestCases.CRM.LateCancel">
    <skipped/>
  </testcase> <!-- testLateCancel -->
  <testcase name="testOrderItemCredit" time="0.0" classname="TestCases.CRM.OrderItemCredit">
    <skipped/>
  </testcase> <!-- testOrderItemCredit -->
  <testcase name="testOrderLevelCredit" time="0.0" classname="TestCases.CRM.OrderLevelCredit">
    <skipped/>
  </testcase> <!-- testOrderLevelCredit -->
  <testcase name="testOTPACHDecline" time="0.0" classname="TestCases.CRM.OTPACHDecline">
    <skipped/>
  </testcase> <!-- testOTPACHDecline -->
  <testcase name="testOTPACHSuccess" time="0.0" classname="TestCases.CRM.OTPACHSuccess">
    <skipped/>
  </testcase> <!-- testOTPACHSuccess -->
  <testcase name="testNSFACH" time="0.0" classname="TestCases.CRM.NSFACH">
    <skipped/>
  </testcase> <!-- testNSFACH -->
  <testcase name="testACHRefund" time="0.0" classname="TestCases.CRM.ACHRefund">
    <skipped/>
  </testcase> <!-- testACHRefund -->
  <testcase name="testOTPDecline" time="0.0" classname="TestCases.CRM.OTPCCDecline">
    <skipped/>
  </testcase> <!-- testOTPDecline -->
  <testcase name="testOTPSuccess" time="0.0" classname="TestCases.CRM.OTPCCSuccess">
    <skipped/>
  </testcase> <!-- testOTPSuccess -->
  <testcase name="testCheckRefund" time="0.0" classname="TestCases.CRM.CheckRefund">
    <skipped/>
  </testcase> <!-- testCheckRefund -->
  <testcase name="testCCRefund" time="0.0" classname="TestCases.CRM.CCRefund">
    <skipped/>
  </testcase> <!-- testCCRefund -->
  <testcase name="testReactivation" time="0.0" classname="TestCases.CRM.Reactivation">
    <skipped/>
  </testcase> <!-- testReactivation -->
  <testcase name="testVacationCancel" time="0.0" classname="TestCases.CRM.VacationCancel">
    <skipped/>
  </testcase> <!-- testVacationCancel -->
  <testcase name="testVacationCreate" time="0.0" classname="TestCases.CRM.VacationCreate">
    <skipped/>
  </testcase> <!-- testVacationCreate -->
  <testcase name="testCreateTicket" time="0.0" classname="TestCases.CRM.CreateTicket">
    <skipped/>
  </testcase> <!-- testCreateTicket -->
  <testcase name="testCheckDeposit" time="0.0" classname="TestCases.ERP.CheckDeposit">
    <skipped/>
  </testcase> <!-- testCheckDeposit -->
  <testcase name="testNSFCheck" time="0.0" classname="TestCases.CRM.NSFCheck">
    <skipped/>
  </testcase> <!-- testNSFCheck -->
  <testcase name="testAddSubscription" time="0.0" classname="TestCases.Magento.AddSubscription">
    <skipped/>
  </testcase> <!-- testAddSubscription -->
  <testcase name="testDeleteSubscription" time="0.0" classname="TestCases.Magento.DeleteSubscription">
    <skipped/>
  </testcase> <!-- testDeleteSubscription -->
  <testcase name="testCustomization" time="0.0" classname="TestCases.Magento.Customization">
    <skipped/>
  </testcase> <!-- testCustomization -->
  <testcase name="testGuestDAB" time="0.0" classname="TestCases.Magento.GuestDonateABox">
    <skipped/>
  </testcase> <!-- testGuestDAB -->
  <testcase name="testGuestGCPurchaseByEmail" time="0.0" classname="TestCases.Magento.GuestGCPurchaseByEmail">
    <skipped/>
  </testcase> <!-- testGuestGCPurchaseByEmail -->
  <testcase name="testGuestGCPurchaseByHand" time="0.0" classname="TestCases.Magento.GuestGCPurchaseByHand">
    <skipped/>
  </testcase> <!-- testGuestGCPurchaseByHand -->
  <testcase name="testLoginout" time="0.0" classname="TestCases.Magento.Loginout">
    <skipped/>
  </testcase> <!-- testLoginout -->
  <testcase name="testSignup" time="197.27" classname="TestCases.Magento.Signup"/>
  <testcase name="testSignupEmailConfirmationCheck" time="0.0" classname="TestCases.Magento.SignupEmailConfirmationCheck">
    <skipped/>
  </testcase> <!-- testSignupEmailConfirmationCheck -->
  <testcase name="testUpdateBillingInfo" time="0.0" classname="TestCases.Magento.UpdateBillingInfo">
    <skipped/>
  </testcase> <!-- testUpdateBillingInfo -->
  <testcase name="testSalesSignup" time="0.001" classname="TestCases.SalesRep.SalesSignup">
    <skipped/>
  </testcase> <!-- testSalesSignup -->
  <testcase name="testUploadTR" time="0.0" classname="TestCases.SalesRep.UploadTR">
    <skipped/>
  </testcase> <!-- testUploadTR -->
</testsuite> <!-- Tests -->
